name: Key Copywriting
favicon: null
layout_spectrum: 0.06139711569994688
typography_spectrum: 0.7876848438754678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9c8b81'
    - '#070915'
    - '#4e525d'
    - '#d2e6fe'
    - '#6f9fe9'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.9416872418951243
  rhythmicContrast: 0.75
purpose: []
