name: Key Copywriting
favicon: null
layout_spectrum: 0.06139711569994688
typography_spectrum: 0.7876848438754678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1832064725458622
  lightness: 0.7788000202272087
  saturation: 0.9416872418951243
  rhythmicContrast: 0.5523760765790939
purpose: []
